replicaCount: 1

image:
  repository: "us-central1-docker.pkg.dev/cloud-ai-police/cloud-ai-police-gar/image-name-1"
  pullPolicy: IfNotPresent
  tag: "tag-1"

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  protocol: TCP
  name: http

container:
  port: 80
