releases:
  - HELM_CHART_DIR: "service-1/helm-chart"
    HELM_RELEASE_NAME: "service-1-release"
    HELM_NAMESPACE: "default"
  - HELM_CHART_DIR: "service-2/helm-chart"
    HELM_RELEASE_NAME: "service-2-release"
    HELM_NAMESPACE: "default"
