releases:
  - HELM_CHART_DIR: "target-backend/helm-chart"
    HELM_RELEASE_NAME: "target-backend-release"
    HELM_NAMESPACE: "default"
  # - HELM_CHART_DIR: "loadgenerator/helm-chart"
  #   HELM_RELEASE_NAME: "loadgenerator-release"
  #   HELM_NAMESPACE: "default"
  # - HELM_CHART_DIR: "target-frontend/helm-chart"
  #   HELM_RELEASE_NAME: "target-frontend-release"
  #   HELM_NAMESPACE: "default"
