images:
  - DOCKER_FILE: "target-backend/Dockerfile.backend"
    DOCKER_CONTEXT_DIR: "target-backend"
    IMAGE_NAME: "target-backend"
    IMAGE_TAG: "latest"
  # - DOCKER_FILE: "target-frontend/Dockerfile.frontend"
  #   DOCKER_CONTEXT_DIR: "target-frontend"
  #   IMAGE_NAME: "target-frontend"
  #   IMAGE_TAG: "latest"
  # - DOCKER_FILE: "loadgenerator/Dockerfile.loadgenerator"
  #   DOCKER_CONTEXT_DIR: "loadgenerator"
  #   IMAGE_NAME: "loadgenerator"
  #   IMAGE_TAG: "latest"
