replicaCount: 1

image:
  repository: "us-central1-docker.pkg.dev/cloud-ai-police/python-gke-server/image-name-2"
  pullPolicy: IfNotPresent
  tag: "tag-2"

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  protocol: TCP
  name: http

container:
  port: 80
