appName: target-frontend
replicaCount: 1


image:
  repository: us-central1-docker.pkg.dev/cloud-ai-police/cloud-ai-police-gar/target-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8501
  targetPort: 80
  protocol: TCP
  name: http
