apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-target-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: target-frontend
  template:
    metadata:
      labels:
        app: target-frontend
    spec:
      containers:
        - name: target-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8501
