apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-target-frontend-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8501
      protocol: TCP
  selector:
    app: target-frontend

